image:
  name: "haskell:8.10.7"
  entrypoint: [""]

stages:
  - make
  - test

make:
  stage: make
  tags:
    - docker2
  script:
    - make

test:
  stage: test
  tags:
    - docker2
  script:
    - make runtests
