resolver: lts-22.41
packages:
  - .
extra-deps:
  - bytestring-0.12.1.0
  - containers-0.7
  - set-extra-1.4.2
  - time-1.9.3
  - binary-0.8.9.2
  - directory-1.3.8.5
  - parsec-3.1.17.0
  - process-1.6.20.0
  - unix-2.8.5.1
  - text-2.1.1
  - filepath-1.4.300.2
  - extra-1.8
  - Cabal-3.14.0.0
  - Cabal-syntax-3.14.0.0
allow-different-user: true
