name: CI

on:
  push:
  pull_request:

jobs:
  make:
    runs-on: ubuntu-latest
    container:
      image: haskell:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Stack root directory
        env:
          STACK_ROOT: /tmp/stack
        run: |
          mkdir -p $STACK_ROOT

      - name: Run make
        env:
          STACK_ROOT: /tmp/stack
        run: make

  test:
    runs-on: ubuntu-latest
    container:
      image: haskell:latest
    needs: make
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Stack root directory
        env:
          STACK_ROOT: /tmp/stack
        run: |
          mkdir -p $STACK_ROOT

      - name: Run tests
        env:
          STACK_ROOT: /tmp/stack
        run: make runtests
