name: CI

on:
  push:
  pull_request:

jobs:
  make:
    runs-on: ubuntu-latest
    container:
      image: haskell:latest
    steps:
      - uses: actions/checkout@v3
      - run: make

  test:
    runs-on: ubuntu-latest
    container:
      image: haskell:latest
    needs: make
    steps:
      - uses: actions/checkout@v3
      - run: make runtests
